name: Build LaTeX document

on:
  push:
    branches:
      - main
    paths:
      - 'doc/syrup_install_guide.tex'  
  pull_request:
    branches:
      - main
    paths:
      - 'doc/syrup_install_guide.tex' 

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Check for changes to syrup_install_guide.tex
        id: check_changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'doc/syrup_install_guide.tex'; then
            echo "File syrup_install_guide.tex has been modified. Proceeding with LaTeX compilation."
            echo "build=true" >> $GITHUB_ENV
          else
            echo "No changes to syrup_install_guide.tex. Skipping LaTeX compilation."
            echo "build=false" >> $GITHUB_ENV
          fi

      - name: Ensure doc/ directory exists
        run: |
          if [ ! -d "doc" ]; then
            echo "Directory doc/ does not exist. Exiting."
            exit 1
          fi

      - name: Compile LaTeX document
        if: env.build == 'true' 
        uses: xu-cheng/latex-action@v3
        with:
          root_file: doc/syrup_install_guide.tex
          texlive_version: latest  

      - name: Upload PDF file
        if: env.build == 'true'  
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: doc/syrup_install_guide.pdf  

      - name: Remove auxiliary files
        if: env.build == 'true' 
        run: |
          find doc/ -type f \( -name "*.aux" -o -name "*.log" -o -name "*.out" -o -name "*.toc" -o -name "*.lof" -o -name "*.lot" -o -name "*.fls" -o -name "*.fdb_latexmk" \) -exec rm -f {} \;
